version: '3.1'

services:

  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./dataB:/var/lib/postgresql/dataB/pgdata
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
